# Generated by Django 4.1.4 on 2022-12-22 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('describtion', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bewertung', models.TextField(max_length=500)),
                ('language', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='Courses/')),
                ('img', models.ImageField(upload_to='Courses/')),
                ('date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Courses_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
